version: "3.10"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ".env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/media:/media_files
      - ./data/static:/static_files
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - python
    restart: unless-stopped
  python:
    build: .
    volumes:
      - .:/code
    env_file:
      - ".env"
    depends_on:
      db:
        condition: service_healthy
      celery_redis:
        condition: service_healthy
    restart: unless-stopped      
  celery_redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli","ping"]

