# Generated by Django 4.0.2 on 2022-02-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_location_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("full_name",), "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ("locatable_identifier",)},
        ),
        migrations.AddField(
            model_name="location",
            name="last_complete_inventory",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
