# Generated by Django 4.0.2 on 2022-02-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_barcodetype_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationlabeltemplate',
            name='label_height',
            field=models.IntegerField(verbose_name='Label height (mm)'),
        ),
    ]
