# Generated by Django 4.1.3 on 2022-11-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='ocr_text',
            field=models.CharField(blank=True, max_length=1024, verbose_name='ocr_text'),
        ),
    ]
