# Generated by Django 4.0.2 on 2022-12-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_itemimage_ocr_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='ocr_text',
            field=models.TextField(blank=True, null=True, verbose_name='ocr text'),
        ),
    ]
