# Generated by Django 4.1.3 on 2022-12-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_itemimage_ocr_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemimage",
            name="ocr_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="ocr_text",
            field=models.TextField(
                blank=True, editable=False, null=True, verbose_name="ocr text"
            ),
        ),
    ]
