# Generated by Django 4.0.2 on 2023-05-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_itemimage_ocr_timestamp_alter_itemimage_ocr_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='last_complete_inventory',
        ),
    ]
