# Generated by Django 5.2.7 on 2025-10-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_location_last_complete_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtype',
            name='moveable',
            field=models.BooleanField(default=False, verbose_name='moveable flag'),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='no_sublocations',
            field=models.BooleanField(default=False, verbose_name='no sublocations flag'),
        ),
    ]
