# Generated by Django 6.1.1 on 2026-09-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_locationtype_moveable_locationtype_no_sublocations"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="deleted"
            ),
        ),
    ]
