# Generated by Django 6.1.1 on 2026-09-20 10:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_item_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Existing descriptions describe the container itself, not its contents.
        migrations.RenameField(
            model_name="location",
            old_name="description",
            new_name="physical_description",
        ),
        migrations.AddField(
            model_name="location",
            name="overview_photo",
            field=models.ImageField(
                blank=True,
                upload_to=inventory.models.get_location_overview_upload_path,
                verbose_name="overview photo",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="physical_description",
            field=models.TextField(blank=True, verbose_name="physical description"),
        ),
        migrations.AddField(
            model_name="location",
            name="summary",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "[\\r\\n]",
                        inverse_match=True,
                        message="The summary must be a single line.",
                    )
                ],
                verbose_name="summary",
            ),
        ),
        migrations.CreateModel(
            name="LocationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_name", models.CharField(blank=True, max_length=150)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("overview_updated", "Overview updated")],
                        default="overview_updated",
                        max_length=40,
                    ),
                ),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "location history entry",
                "verbose_name_plural": "location history entries",
                "ordering": ("-created_at", "-pk"),
                "default_permissions": ("view",),
            },
        ),
    ]
