# Generated by Django 6.1.1 on 2026-10-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_location_overview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemlocation",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="positive numbers are precise, negative numbers are rough estimates. -1 is 'few' and -9999 is 'many'. Empty means unknown.",
                max_digits=16,
                null=True,
                verbose_name="amount",
            ),
        ),
    ]
