# Generated by Django 6.1.1 on 2026-10-08 23:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def grant_stock_changes_to_local_group(apps, schema_editor):
    # ZAM-local may add and change inventory, which includes removing and adding stock.
    alias = schema_editor.connection.alias
    group, _ = apps.get_model("auth", "Group").objects.using(alias).get_or_create(name="ZAM-local")
    content_type, _ = apps.get_model("contenttypes", "ContentType").objects.using(alias).get_or_create(
        app_label="inventory", model="stockchange",
    )
    permission, _ = apps.get_model("auth", "Permission").objects.using(alias).get_or_create(
        content_type=content_type, codename="add_stockchange",
        defaults={"name": "Can add stock change"},
    )
    group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_itemlocation_unknown_amount"),
        ("accounts", "0002_zam_local_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="date",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("decrease", "Removal"), ("increase", "Restock")],
                        max_length=10,
                        verbose_name="direction",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("own_use", "ZAM's own use"),
                            ("recount_lost", "Recount (lost or correction)"),
                            ("destruction", "Destruction"),
                            ("other", "Other"),
                            ("purchase", "Purchase"),
                            ("donation", "Donation"),
                            ("recount_found", "Recount (found or unknown origin)"),
                        ],
                        max_length=20,
                        verbose_name="reason",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("dialog", "Stock dialog"),
                            ("item_form", "Item form"),
                            ("admin", "Admin"),
                            ("dissolution", "Location dissolution"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="source",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=512, verbose_name="item name"),
                ),
                (
                    "location_name",
                    models.CharField(max_length=512, verbose_name="location name"),
                ),
                (
                    "amount_before",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=16,
                        null=True,
                        verbose_name="amount before",
                    ),
                ),
                (
                    "amount_after",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=16,
                        null=True,
                        verbose_name="amount after",
                    ),
                ),
                (
                    "entry_removed",
                    models.BooleanField(
                        default=False, verbose_name="removed from location"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Always positive; empty if unknown.",
                        max_digits=16,
                        null=True,
                        verbose_name="changed amount",
                    ),
                ),
                (
                    "is_estimate",
                    models.BooleanField(default=False, verbose_name="estimated"),
                ),
                (
                    "unit",
                    models.CharField(max_length=8, verbose_name="measurement unit"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="sale price per unit",
                    ),
                ),
                (
                    "sale_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="sale value",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.item",
                        verbose_name="item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.location",
                        verbose_name="location",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock change",
                "verbose_name_plural": "stock changes",
                "ordering": ("-created_at", "-pk"),
                "default_permissions": ("add", "view"),
            },
        ),
        migrations.RunPython(grant_stock_changes_to_local_group, migrations.RunPython.noop),
    ]
